version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/editoast/"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry:
        patterns:
          - "*opentelemetry*"
    commit-message:
      prefix: "editoast:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "area:editoast"
  - package-ecosystem: "cargo"
    directory: "/gateway/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "gateway:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "area:gateway"
  - package-ecosystem: "npm"
    directory: "/front/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: "front:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "area:front"
  # Poetry uses the "pip" value:
  # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-the-dependabotyml-file
  - package-ecosystem: "pip"
    directory: "/python/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "python:"
    open-pull-requests-limit: 0
    labels:
      - "dependencies"
      - "area:railjson"
  - package-ecosystem: "pip"
    directory: "/tests/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "tests:"
    open-pull-requests-limit: 0
    labels:
      - "dependencies"
      - "area:integration-tests"
  - package-ecosystem: "gradle"
    directory: "/core/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "core:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "area:core"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "actions:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "area:actions"
