[package]
name = "editoast"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0"

[workspace]
members = [".", "editoast_common", "editoast_derive", "editoast_schemas"]

[workspace.dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
derivative = "2.2.0"
editoast_common = { path = "./editoast_common" }
enum-map = "2.7.3"
geojson = "*"
geos = { version = "8.3.1", features = ["json"] }
mvt = "0.9.0"
postgis_diesel = { version = "2.3.1", features = ["serde"] }
rand = "0.8.5"
rangemap = "1.5.1"
serde = "1.0.199"
serde_derive = "1.0.195"
serde_json = "1.0.116"
strum = { version = "0.26.2", features = ["derive"] }
thiserror = "1.0.59"
utoipa = { version = "4.2.0", features = ["actix_extras", "chrono", "uuid"] }
uuid = { version = "1.8.0", features = ["v4"] }

[dependencies]
# For batch dependcy updates see https://osrd.fr/en/docs/guides/contribute/batch-updating-dependencies/

actix-cors = "0.7.0"
actix-files = "0.6.5"
actix-http = "3.6.0"
actix-multipart = "0.6.1"
actix-web = "4.5.1"
actix-web-opentelemetry = { version = "0.17.0", features = ["awc"] }
async-trait = "0.1.80"
cfg-if = "1.0.0"
chashmap = "2.2.2"
chrono.workspace = true
clap = { version = "4.5.4", features = ["derive", "env"] }
colored = "2.1.0"
derivative.workspace = true
diesel = { version = "2.1.5", features = [
  "chrono",
  "postgres",
  "serde_json",
  "uuid",
] }
diesel-async = { version = "0.4.1", features = ["deadpool", "postgres"] }
diesel_json = "0.2.1"
editoast_common = { workspace = true }
editoast_derive = { path = "./editoast_derive" }
editoast_schemas = { path = "./editoast_schemas" }
enum-map.workspace = true
enumset = "1.1.3"
futures = "0.3.30"
futures-util = "*"
geos.workspace = true
heck = "0.5.0"
image = "0.25.1"
inventory = "0.3"
itertools = "0.12.1"
json-patch = "1.2.0"
mvt.workspace = true
openssl = "*"
opentelemetry = "0.22.0"
opentelemetry-datadog = { version = "0.10.0", features = ["reqwest-client"] }
opentelemetry-otlp = "0.15.0"
opentelemetry-semantic-conventions = "0.14.0"
opentelemetry_sdk = { version = "0.22.1", features = ["rt-tokio", "trace"] }
osm4routing = "0.6.1"
osmpbfreader = "0.16.1"
paste = "1.0.14"
pathfinding = "4.9.1"
postgis_diesel.workspace = true
postgres-openssl = "0.5.0"
rand.workspace = true
rangemap.workspace = true
redis = { version = "0.25.3", features = [
  "cluster-async",
  "connection-manager",
  "tokio-comp",
  "tokio-native-tls-comp",
] }
reqwest = { version = "0.11.27", features = ["json"] }
sentry = "0.32.3"
sentry-actix = "0.32.3"
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
serde_qs = { version = "0.12.0", features = ["actix4"] }
serde_yaml = "0.9.34"
sha1 = "0.10"
strum.workspace = true
thiserror.workspace = true
tokio = "*"
tokio-postgres = "*"
tracing = { version = "0.1.40", features = ["log"] }
tracing-opentelemetry = "0.23.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.0"
utoipa.workspace = true
uuid.workspace = true
validator = { version = "0.18.1", features = ["derive"] }

[dev-dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
pretty_assertions = "1.4.0"
rstest = "0.18.2"
serial_test = "3.1.1"
tempfile = "3.10.1"
