[package]
name = "editoast"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0"

[workspace]
members = [".", "editoast_derive", "osrd_containers"]

[workspace.dependencies]
rangemap = "1.4.0"
serde = "1.0.195"
serde_derive = "1.0.195"
serde_json = "1.0.115"
utoipa = { version = "4.2.0", features = ["actix_extras", "chrono", "uuid"] }

[dependencies]
# For batch dependcy updates see https://osrd.fr/en/docs/guides/contribute/batch-updating-dependencies/

async-trait = "0.1.79"
chashmap = "2.2.2"
clap = { version = "4.5.4", features = ["derive", "env"] }
colored = "2.1.0"
chrono = { version = "0.4.37", features = ["serde"] }
derivative = "2.2.0"
uuid = { version = "1.8.0", features = ["v4"] }
diesel = { version = "2.1.4", features = [
    "postgres",
    "serde_json",
    "chrono",
    "uuid",
] }
diesel-async = { version = "0.4.1", features = ["postgres", "deadpool"] }
tokio = "*"
tokio-postgres = "*"
postgres-openssl = "0.5.0"
openssl = "*"
futures-util = "*"
diesel_json = "0.2.1"
image = "0.24.8"
json-patch = "1.2.0"
pathfinding = "4.8.2"
rand = "0.8.5"
actix-files = "0.6.5"
actix-web = "4.4.1"
actix-http = "3.5.1"
actix-cors = "0.7.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = { version = "0.1.40", features = ["log"] }
redis = { version = "0.24.0", features = [
    "tokio-comp",
    "connection-manager",
    "cluster-async",
    "tokio-native-tls-comp",
] }
sentry = "0.32.1"
sentry-actix = "0.32.1"
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
serde_yaml = "0.9.34"
sha1 = "0.10"
strum = "0.25.0"
strum_macros = "0.25.3"
thiserror = "1.0.56"
enum-map = "2.7.3"
editoast_derive = { path = "./editoast_derive" }
osrd_containers = { path = "./osrd_containers" }
mvt = "0.9.0"
futures = "0.3.30"
postgis_diesel = { version = "2.3.0", features = ["serde"] }
geos = { version = "8.3.0", features = ["json"] }
rangemap.workspace = true
actix-multipart = "0.6.1"
reqwest = { version = "0.11.23", features = ["json"] }
osm4routing = "0.5.9"
osmpbfreader = "0.16.1"
itertools = "0.12.0"
utoipa.workspace = true
paste = "1.0.14"
url = "2.5.0"
cfg-if = "1.0.0"
validator = { version = "0.16.1", features = ["derive"] }
inventory = "0.3"
heck = "0.4.1"
iso8601 = "0.6.1"
opentelemetry = "0.21.0"
opentelemetry_sdk = { version = "0.21.0", features = ["rt-tokio", "trace"] }
opentelemetry-otlp = "0.14.0"
opentelemetry-datadog = { version = "0.9.0", features = ["reqwest-client"] }
opentelemetry-semantic-conventions = "0.13.0"
tracing-opentelemetry = "0.22.0"
actix-web-opentelemetry = { version = "0.16.0", features = ["awc"] }
serde_qs = { version = "0.12.0", features = ["actix4"] }
enumset = "1.1.3"

[dev-dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
rstest = "0.18.2"
tempfile = "3.9.0"
pretty_assertions = "1.4.0"
serial_test = "3.0.0"
