name: Test osrd_schemas

on:
  workflow_dispatch:
  pull_request:
    paths:
      - python/osrd_schemas/**
      - .github/workflows/osrd_schemas.yml
      - front/src/reducers/osrdconf/infra_schema.json
  merge_group:
    paths:
      - python/osrd_schemas/**
      - .github/workflows/osrd_schemas.yml
      - front/src/reducers/osrdconf/infra_schema.json
  push:
    branches:
      - dev
      - staging
      - prod

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"
      - name: Install dependencies
        run: |
          cd python/osrd_schemas
          poetry install --only dev
      - name: Flake8
        run: |
          cd python/osrd_schemas
          poetry run pflake8 --config ./pyproject.toml --output-file flake8.xml --format junit-xml
      - name: Publish flake8 report
        uses: mikepenz/action-junit-report@v3
        if: failure()
        with:
          report_paths: flake8.xml
      - name: Black
        run: |
          cd python/osrd_schemas
          poetry run black . --check
      - name: Isort
        run: |
          cd python/osrd_schemas
          poetry run isort . --check

  infra_schema-sync:
    name: Check infra_schema.json
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            # run the CI on the actual latest commit of the PR, not the attempted merge
            ref: ${{ github.event.pull_request.head.sha }}
        - name: Install poetry
          run: pipx install poetry
        - uses: actions/setup-python@v4
          with:
            python-version: "3.11"
            cache: "poetry"
        - name: Check infra_schema.json sync
          run: |
            cd python/osrd_schemas
            poetry install --no-interaction --no-root
            poetry run python osrd_schemas/infra.py > current_infra_schema.json
            diff current_infra_schema.json ../../front/src/reducers/osrdconf/infra_schema.json
