name: release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    outputs:
      stable_tags: ${{ steps.bake-metadata.outputs.stable_tags }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make bake metadata
        id: bake-metadata
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          set -eo pipefail
          echo ::group::Github context
          python3 -m json.tool <<< "${GITHUB_CONTEXT}"
          echo ::endgroup::

          echo ::group::Bake metadata
          .github/scripts/bake-metadata.py | tee bake-metadata.json
          echo
          echo ::endgroup::

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.12.0
          driver-opts: image=moby/buildkit:v0.12.3
          buildkitd-flags: --debug

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: '$' # special user for authenticating as a gh actions worker
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          docker buildx bake --file=docker/docker-bake.hcl --file=bake-metadata.json release --push
